DeleteCredentialConfigForMdoc:
  InjiCertify_DeleteCredentialConfig_mdl_all_Valid_Smoke:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_mdl_DeleteCredentialConfig_01
    description: delete Credential configuration for mdoc with all valid parameters
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/mDocMDL/DeleteCredentialConfigurationForMdoc/DeleteCredentialConfigurationForMdoc
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_mdl_all_Valid_Smoke_sid_id$"
      }'
    output: '{
      "responseCode": "200"    
    }'

  InjiCertify_DeleteCredentialConfig_mdl_without_msomdocClaims:
    endPoint: $INJICERTIFYBASEURL$/v1/certify/credential-configurations/{configurationId}
    uniqueIdentifier: TC_InjiCertify_mdl_DeleteCredentialConfig_02
    description: Delete Credential configuration for mdoc without msomdocclaims which was added
    role: noauth    
    checkOnlyStatusCodeInResponse: true
    restMethod: delete
    inputTemplate: injicertify/mDocMDL/DeleteCredentialConfigurationForMdoc/DeleteCredentialConfigurationForMdoc
    outputTemplate: injicertify/responseCode
    input: '{
        "configurationId": "$ID:AddCredentialConfig_mdl_withoutClaims_sid_id$"
      }'
    output: '{
      "responseCode": "200"    
    }'