#!/usr/bin/env bash
# =====================================================================================
# generate-config.sh
#
# Bakes your public GitHub Pages base URL + issuer did:web into:
#   1. certify_init_custom.sql            -> credential_config rows (base64 VC templates)
#   2. config/certify-postgres-custom.properties -> the did-url
#   3. custom-issuer/dist/contexts/*.json -> JSON-LD @context files ready to upload
#
# Why a generator: the VC template is stored base64-encoded in credential_config, and
# the @context URL lives *inside* that template, so it can't be sed-replaced after
# encoding. This script substitutes first, then encodes.
#
# Usage:
#   ./generate-config.sh <BASE_URL> [ISSUER_DID]
#
#   BASE_URL    Public GitHub Pages root, e.g. https://janedoe.github.io/inji-config
#   ISSUER_DID  (optional) issuer did:web. If omitted, derived from BASE_URL as
#               did:web:<host>:<path...>:inji-issuer
#
# Example:
#   ./generate-config.sh https://janedoe.github.io/inji-config
#     -> ISSUER_DID = did:web:janedoe.github.io:inji-config:inji-issuer
#     -> did.json must be hosted at https://janedoe.github.io/inji-config/inji-issuer/did.json
#     -> contexts at https://janedoe.github.io/inji-config/contexts/{student,insurance}.json
# =====================================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STACK_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

BASE_URL="${1:-}"
if [[ -z "${BASE_URL}" ]]; then
  echo "ERROR: BASE_URL is required." >&2
  echo "Usage: $0 <BASE_URL> [ISSUER_DID]" >&2
  echo "Example: $0 https://janedoe.github.io/inji-config" >&2
  exit 1
fi
BASE_URL="${BASE_URL%/}"   # strip trailing slash

# Derive ISSUER_DID from BASE_URL if not provided:
#   https://host/seg1/seg2  ->  did:web:host:seg1:seg2:inji-issuer
if [[ -n "${2:-}" ]]; then
  ISSUER_DID="$2"
else
  no_scheme="${BASE_URL#https://}"
  no_scheme="${no_scheme#http://}"
  ISSUER_DID="did:web:${no_scheme//\//:}:inji-issuer"
fi

STUDENT_CTX_URL="${BASE_URL}/contexts/student.json"
INSURANCE_CTX_URL="${BASE_URL}/contexts/insurance.json"

echo "BASE_URL          = ${BASE_URL}"
echo "ISSUER_DID        = ${ISSUER_DID}"
echo "STUDENT_CTX_URL   = ${STUDENT_CTX_URL}"
echo "INSURANCE_CTX_URL = ${INSURANCE_CTX_URL}"
echo

# ---- 1. Base64-encode the VC templates with the real context URL substituted --------
student_tpl="$(sed "s#__STUDENT_CTX_URL__#${STUDENT_CTX_URL}#g" "${SCRIPT_DIR}/templates/student-identity-vc.json")"
insurance_tpl="$(sed "s#__INSURANCE_CTX_URL__#${INSURANCE_CTX_URL}#g" "${SCRIPT_DIR}/templates/insurance-vc.json")"
STUDENT_B64="$(printf '%s' "${student_tpl}" | base64 -w0)"
INSURANCE_B64="$(printf '%s' "${insurance_tpl}" | base64 -w0)"

# ---- 2. Emit dist context files ready to publish on GitHub Pages --------------------
mkdir -p "${SCRIPT_DIR}/dist/contexts"
sed "s#__BASE_URL__#${BASE_URL}#g" "${SCRIPT_DIR}/context/student.json"   > "${SCRIPT_DIR}/dist/contexts/student.json"
sed "s#__BASE_URL__#${BASE_URL}#g" "${SCRIPT_DIR}/context/insurance.json" > "${SCRIPT_DIR}/dist/contexts/insurance.json"

# ---- 3. Patch the did-url into the Postgres plugin properties ------------------------
PROPS="${STACK_DIR}/config/certify-postgres-custom.properties"
sed -i.bak "s#^mosip.certify.data-provider-plugin.did-url=.*#mosip.certify.data-provider-plugin.did-url=${ISSUER_DID}#" "${PROPS}"
rm -f "${PROPS}.bak"

# ---- 4. Generate certify_init_custom.sql (credential_config rows) -------------------
OUT_SQL="${STACK_DIR}/certify_init_custom.sql"
cat > "${OUT_SQL}" <<SQL
-- =====================================================================================
-- GENERATED by custom-issuer/generate-config.sh — DO NOT EDIT BY HAND.
-- Re-run the generator to regenerate after changing the host/DID or templates.
--
-- BASE_URL   = ${BASE_URL}
-- ISSUER_DID = ${ISSUER_DID}
--
-- Inserts the credential_config rows for the custom Postgres-backed issuers. Runs after
-- certify_init.sql during Postgres container initialization (alphabetical order).
-- =====================================================================================
\\c inji_certify postgres

-- Issuer 1: University -> StudentIdentityCredential
INSERT INTO certify.credential_config (
    credential_config_key_id, config_id, status, vc_template, doctype, sd_jwt_vct,
    context, credential_type, credential_format, did_url, key_manager_app_id,
    key_manager_ref_id, signature_algo, signature_crypto_suite, sd_claim, display,
    display_order, scope, cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported, proof_types_supported, credential_subject,
    mso_mdoc_claims, plugin_configurations, credential_status_purpose, qr_settings,
    qr_signature_algo, cr_dtimes, upd_dtimes
) VALUES (
    'StudentIdentityCredential',
    gen_random_uuid()::VARCHAR(255),
    'active',
    '${STUDENT_B64}',
    NULL,
    NULL,
    '${STUDENT_CTX_URL},https://www.w3.org/2018/credentials/v1',
    'StudentIdentityCredential,VerifiableCredential',
    'ldp_vc',
    '${ISSUER_DID}',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "University Student ID", "locale": "en", "logo": {"url": "https://mosip.github.io/inji-config/logos/agro-vertias-logo.png", "alt_text": "University Logo"}, "background_color": "#0b3d91", "text_color": "#FFFFFF"}]'::JSONB,
    ARRAY['fullName', 'studentId', 'program', 'enrollmentYear', 'email'],
    'student_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"fullName": {"display": [{"name": "Full Name", "locale": "en"}]}, "studentId": {"display": [{"name": "Student ID", "locale": "en"}]}, "program": {"display": [{"name": "Program", "locale": "en"}]}, "enrollmentYear": {"display": [{"name": "Enrollment Year", "locale": "en"}]}, "email": {"display": [{"name": "Email", "locale": "en"}]}}'::JSONB,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL
);

-- Issuer 2: Health Authority -> InsuranceCredential
INSERT INTO certify.credential_config (
    credential_config_key_id, config_id, status, vc_template, doctype, sd_jwt_vct,
    context, credential_type, credential_format, did_url, key_manager_app_id,
    key_manager_ref_id, signature_algo, signature_crypto_suite, sd_claim, display,
    display_order, scope, cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported, proof_types_supported, credential_subject,
    mso_mdoc_claims, plugin_configurations, credential_status_purpose, qr_settings,
    qr_signature_algo, cr_dtimes, upd_dtimes
) VALUES (
    'InsuranceCredential',
    gen_random_uuid()::VARCHAR(255),
    'active',
    '${INSURANCE_B64}',
    NULL,
    NULL,
    '${INSURANCE_CTX_URL},https://www.w3.org/2018/credentials/v1',
    'InsuranceCredential,VerifiableCredential',
    'ldp_vc',
    '${ISSUER_DID}',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "Health Insurance Card", "locale": "en", "logo": {"url": "https://api.collab.mosip.net/inji/mosip-logo.png", "alt_text": "Health Authority Logo"}, "background_color": "#107c41", "text_color": "#FFFFFF"}]'::JSONB,
    ARRAY['fullName', 'policyNumber', 'plan', 'coverageValidUntil'],
    'insurance_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"fullName": {"display": [{"name": "Full Name", "locale": "en"}]}, "policyNumber": {"display": [{"name": "Policy Number", "locale": "en"}]}, "plan": {"display": [{"name": "Plan", "locale": "en"}]}, "coverageValidUntil": {"display": [{"name": "Valid Until", "locale": "en"}]}}'::JSONB,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL
);
SQL

echo "Wrote: ${OUT_SQL}"
echo "Wrote: ${SCRIPT_DIR}/dist/contexts/student.json"
echo "Wrote: ${SCRIPT_DIR}/dist/contexts/insurance.json"
echo "Patched did-url in: ${PROPS}"
echo
echo "NEXT STEPS:"
echo "  1. Start the stack so Certify generates its DID document:"
echo "       ./setup.sh && docker compose up -d"
echo "  2. Fetch the DID document and publish it to GitHub Pages at:"
echo "       ${BASE_URL}/inji-issuer/did.json"
echo "     curl -s http://localhost:8090/v1/certify/.well-known/did.json"
echo "  3. Publish the two context files (custom-issuer/dist/contexts/) to:"
echo "       ${STUDENT_CTX_URL}"
echo "       ${INSURANCE_CTX_URL}"
echo "  4. Recreate so the generated SQL is applied (fresh DB):"
echo "       docker compose down -v && ./setup.sh && docker compose up -d"
