package inji.utils.testdatamanager;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import inji.models.Uin;

public class UINManager {

    private static final BlockingQueue<Uin> availableUINs = new LinkedBlockingQueue<>();

    static {
        int totalUINs = 5;
        for (int i = 1; i <= totalUINs; i++) {
            String prefix = "AddIdentity_withValidParameters_smoke_UIN" + i + "_Pos_";
            availableUINs.add(new Uin(
                    autoGeneratedIDValueCache.get(prefix + "UIN"),
                    autoGeneratedIDValueCache.get(prefix + "PHONE"),
                    autoGeneratedIDValueCache.get(prefix + "EMAIL")
            ));
        }
    }

    //Sample data, data can be passed in this way as well
//    static {
//        availableUINs.add(new Uin("6379306910", "3602485447", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("2038930429", "+4317909080", "Mimoto_AddIdentity_Binding_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("3985781534", "1048876755", "Mimoto_AddIdentity_downloadIssuerCredential_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4517095619", "2002563005", "Mimoto_AddIdentity_downloadIssuerCredentialWithGoogleLogin_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4527046734", "8548612682", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_0cb_@mosip.net"));
//    }

    public static Uin acquireUIN() throws InterruptedException {
        return availableUINs.take();
    }

    public static void releaseUIN(Uin uin) {
        availableUINs.offer(uin);
    }

    public static Uin acquireUINWithTimeout(long timeoutSeconds) throws InterruptedException {
        return availableUINs.poll(timeoutSeconds, TimeUnit.SECONDS);
    }
}
