
package stepdefinitions;

import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.mosip.testrig.apirig.utils.AdminTestUtil;

import io.mosip.testrig.apirig.utils.NotificationListener;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.openqa.selenium.WebDriver;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.ExtentTest;

import pages.MosipCredentials;
import pages.SetNetwork;
import utils.*;

import static org.testng.Assert.assertTrue;

import java.io.IOException;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Base64;

import base.BasePage;
import utils.testdatamanager.UINManager;

public class StepDefMosipCredentials {
	String pageTitle;
	public WebDriver driver;
	BaseTest baseTest;
	private MosipCredentials mosipCredentials;
	private SetNetwork setNetwork;
	private BasePage basePage;
	private InjiWebUtil injiWebUtil = new InjiWebUtil();

	ExtentTest test = ExtentReportManager.getTest();

	public StepDefMosipCredentials() {
		this.baseTest = new BaseTest();
		this.driver = baseTest.getDriver();
		this.mosipCredentials = new MosipCredentials(driver);
		this.setNetwork = new SetNetwork();
		this.basePage = new BasePage();
	}

	@Then("User verifies that the mock verifiable credential by e-Signet is displayed")
	public void user_verify_mock_verifiable_credential_by_e_signet_displayed() {
		assertTrue(mosipCredentials.isMockVerifiableCredentialDisplayed(),
				"Mock verifiable credential by e-Signet is not displayed");
	}

	@When("User clicks on the mock verifiable credential by e-Signet button")
	public void user_click_on_mock_verifiable_credential_by_e_signet_button() {
		mosipCredentials.clickOnMockVerifiableCredential();
	}

	@When("User enters the UIN")
	public void user_enter_the_uin() {
		String uin = AdminTestUtil.autoGeneratedIDValueCache.get("AddIdentity_withValidParameters_smoke_Pos_UIN");
		mosipCredentials.enterVid(uin);
	}

	@When("User enter the uin")
	public void user_enter_the() {
		mosipCredentials.enterVid(UINManager.getUin());
	}

	@When("User click on getOtp button")
	public void user_click_on_get_otp_button() {
		int maxAttempts = 3;
		int otpPageWaitTime = InjiWebConfigManager.getOtpVerificationPageWaitTimeInSeconds();
		Exception lastException = null;
		for (int attempt = 1; attempt <= maxAttempts; attempt++) {
			try {
				NotificationListener.markRequestStart();
				mosipCredentials.clickOnGetOtpButton();
				test.log(Status.INFO, "Clicked on the Get OTP button. Attempt: " + attempt + "/" + maxAttempts);

				if (mosipCredentials.isOtpVerificationPageDisplayed(otpPageWaitTime)) {
					test.log(Status.INFO, "OTP verification page displayed after attempt " + attempt);
					return;
				}

				test.log(Status.WARNING, "OTP verification page not displayed after Get OTP attempt "
						+ attempt + "/" + maxAttempts + ". Retrying if attempts remain.");
			} catch (Exception e) {
				lastException = e;
				test.log(Status.WARNING, "Get OTP attempt " + attempt + "/" + maxAttempts
						+ " failed: " + e.getMessage());
			}
		}

		throw new RuntimeException("OTP verification page was not displayed after "
				+ maxAttempts + " Get OTP attempts", lastException);
	}

	@When("User enter the otp")
	public void user_enter_the_otp() {
		mosipCredentials.enterOtp(baseTest.getDriver(), injiWebUtil.uinGetOtp());
	}

	@When("User click on mosip national id by e-signet button")
	public void user_click_on_mosip_national_id_by_e_signet_button() {
		mosipCredentials.clickOnMosipNationalId();
	}

	@When("User verify login page lables")
	public void user_verify_login_page_labels() {
		assertTrue(mosipCredentials.isLoginPageLableDisplayed(), "Login page label is not displayed");
	}

	@When("User verify vid input box header")
	public void user_verify_vid_input_box_header() {
		assertTrue(mosipCredentials.isVidInputBoxHeaderDisplayed(), "VID input box header is not displayed");
	}

	@Then("User verify pdf is downloaded")
	public String user_verify_pdf_is_downloaded() throws IOException, InterruptedException {
		File pdfFile;
		if (BaseTest.isBrowserStackRunEnabled()) {
			baseTest.getJse().executeScript(
					"browserstack_executor: {\"action\": \"fileExists\", \"arguments\": {\"fileName\": \""
							+ mosipCredentials.pdfName + "\"}}");
			baseTest.getJse().executeScript(
					"browserstack_executor: {\"action\": \"getFileProperties\", \"arguments\": {\"fileName\": \""
							+ mosipCredentials.pdfName + "\"}}");

			String base64EncodedFile = (String) baseTest.getJse().executeScript(
					"browserstack_executor: {\"action\": \"getFileContent\", \"arguments\": {\"fileName\": \""
							+ mosipCredentials.pdfName + "\"}}");
			byte[] data = Base64.getDecoder().decode(base64EncodedFile);
			OutputStream stream = new FileOutputStream(mosipCredentials.pdfName);
			stream.write(data);
			stream.close();
			pdfFile = new File(System.getProperty("user.dir"), mosipCredentials.pdfName);
		} else {
			pdfFile = waitForDownloadedFile(mosipCredentials.pdfName, BasePage.getConfiguredWaitTimeInSeconds());
		}

		PDDocument document = PDDocument.load(pdfFile);

		PDFTextStripper stripper = new PDFTextStripper();
		String text = stripper.getText(document);
		return text;
	}

	private File waitForDownloadedFile(String fileName, int timeoutSeconds) throws InterruptedException {
		File downloadsDir = new File(System.getProperty("user.dir"), "downloads");
		File targetFile = new File(downloadsDir, fileName);
		long deadline = System.currentTimeMillis() + (timeoutSeconds * 1000L);

		while (System.currentTimeMillis() < deadline) {
			if (targetFile.exists() && targetFile.length() > 0) {
				return targetFile;
			}
			Thread.sleep(1000);
		}

		throw new IllegalStateException("PDF file not found in local downloads directory: " + targetFile.getAbsolutePath());
	}

	@Then("User verifies mosip vc is downloaded successfully")
	public void user_verifies_mosip_vc_downloaded_successfully() {
		assertTrue(mosipCredentials.isMosipVcDownloadedSuccessfully(),
				"MOSIP VC download failed: either the download-result page did not appear within 90s, "
						+ "or the VC card was not rendered on the result page within 30s after that");
	}

	@Then("User verifies 'Downloading in Progress' text")
	public void user_verify_downloading_in_progress_displayed() {
		assertTrue(mosipCredentials.isDownloadingDescriptionTextDisplayed(),
				"'Downloading in Progress' text is not displayed");
	}

	@Then("User verify downloading in progress text")
	public void user_VerifyDownloadingInProgressDisplayed() {
		assertTrue(mosipCredentials.isDownloadingDescriptionTextDisplayed(),
				"'Downloading in Progress' text is not displayed");
	}

}