-- =====================================================================================
-- GENERATED by custom-issuer/generate-config.sh — DO NOT EDIT BY HAND.
-- Re-run the generator to regenerate after changing the host/DID or templates.
--
-- BASE_URL   = https://viitoradmin.github.io/inji-digital-health-id
-- ISSUER_DID = did:web:viitoradmin.github.io:inji-digital-health-id:inji-issuer
--
-- Inserts the credential_config rows for the custom Postgres-backed issuers. Runs after
-- certify_init.sql during Postgres container initialization (alphabetical order).
-- =====================================================================================
\c inji_certify postgres

-- Issuer 1: University -> StudentIdentityCredential
INSERT INTO certify.credential_config (
    credential_config_key_id, config_id, status, vc_template, doctype, sd_jwt_vct,
    context, credential_type, credential_format, did_url, key_manager_app_id,
    key_manager_ref_id, signature_algo, signature_crypto_suite, sd_claim, display,
    display_order, scope, cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported, proof_types_supported, credential_subject,
    mso_mdoc_claims, plugin_configurations, credential_status_purpose, qr_settings,
    qr_signature_algo, cr_dtimes, upd_dtimes
) VALUES (
    'StudentIdentityCredential',
    gen_random_uuid()::VARCHAR(255),
    'active',
    'ewogICJAY29udGV4dCI6IFsKICAgICJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsCiAgICAiaHR0cHM6Ly92aWl0b3JhZG1pbi5naXRodWIuaW8vaW5qaS1kaWdpdGFsLWhlYWx0aC1pZC9jb250ZXh0cy9zdHVkZW50Lmpzb24iLAogICAgImh0dHBzOi8vdzNpZC5vcmcvc2VjdXJpdHkvc3VpdGVzL2VkMjU1MTktMjAyMC92MSIKICBdLAogICJpc3N1ZXIiOiAiJHtfaXNzdWVyfSIsCiAgInR5cGUiOiBbCiAgICAiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLAogICAgIlN0dWRlbnRJZGVudGl0eUNyZWRlbnRpYWwiCiAgXSwKICAiaXNzdWFuY2VEYXRlIjogIiR7dmFsaWRGcm9tfSIsCiAgImV4cGlyYXRpb25EYXRlIjogIiR7dmFsaWRVbnRpbH0iLAogICJjcmVkZW50aWFsU3ViamVjdCI6IHsKICAgICJpZCI6ICIke19ob2xkZXJJZH0iLAogICAgImZ1bGxOYW1lIjogIiR7ZnVsbE5hbWV9IiwKICAgICJzdHVkZW50SWQiOiAiJHtzdHVkZW50SWR9IiwKICAgICJwcm9ncmFtIjogIiR7cHJvZ3JhbX0iLAogICAgImVucm9sbG1lbnRZZWFyIjogIiR7ZW5yb2xsbWVudFllYXJ9IiwKICAgICJlbWFpbCI6ICIke2VtYWlsfSIKICB9Cn0=',
    NULL,
    NULL,
    'https://www.w3.org/2018/credentials/v1,https://viitoradmin.github.io/inji-digital-health-id/contexts/student.json',
    'StudentIdentityCredential,VerifiableCredential',
    'ldp_vc',
    'did:web:viitoradmin.github.io:inji-digital-health-id:inji-issuer',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "University Student ID", "locale": "en", "logo": {"url": "https://mosip.github.io/inji-config/logos/agro-vertias-logo.png", "alt_text": "University Logo"}, "background_color": "#0b3d91", "text_color": "#FFFFFF"}]'::JSONB,
    ARRAY['fullName', 'studentId', 'program', 'enrollmentYear', 'email'],
    'student_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"fullName": {"display": [{"name": "Full Name", "locale": "en"}]}, "studentId": {"display": [{"name": "Student ID", "locale": "en"}]}, "program": {"display": [{"name": "Program", "locale": "en"}]}, "enrollmentYear": {"display": [{"name": "Enrollment Year", "locale": "en"}]}, "email": {"display": [{"name": "Email", "locale": "en"}]}}'::JSONB,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL
);

-- Issuer 2: Health Authority -> InsuranceCredential
INSERT INTO certify.credential_config (
    credential_config_key_id, config_id, status, vc_template, doctype, sd_jwt_vct,
    context, credential_type, credential_format, did_url, key_manager_app_id,
    key_manager_ref_id, signature_algo, signature_crypto_suite, sd_claim, display,
    display_order, scope, cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported, proof_types_supported, credential_subject,
    mso_mdoc_claims, plugin_configurations, credential_status_purpose, qr_settings,
    qr_signature_algo, cr_dtimes, upd_dtimes
) VALUES (
    'InsuranceCredential',
    gen_random_uuid()::VARCHAR(255),
    'active',
    'ewogICJAY29udGV4dCI6IFsKICAgICJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsCiAgICAiaHR0cHM6Ly92aWl0b3JhZG1pbi5naXRodWIuaW8vaW5qaS1kaWdpdGFsLWhlYWx0aC1pZC9jb250ZXh0cy9pbnN1cmFuY2UuanNvbiIsCiAgICAiaHR0cHM6Ly93M2lkLm9yZy9zZWN1cml0eS9zdWl0ZXMvZWQyNTUxOS0yMDIwL3YxIgogIF0sCiAgImlzc3VlciI6ICIke19pc3N1ZXJ9IiwKICAidHlwZSI6IFsKICAgICJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsCiAgICAiSW5zdXJhbmNlQ3JlZGVudGlhbCIKICBdLAogICJpc3N1YW5jZURhdGUiOiAiJHt2YWxpZEZyb219IiwKICAiZXhwaXJhdGlvbkRhdGUiOiAiJHt2YWxpZFVudGlsfSIsCiAgImNyZWRlbnRpYWxTdWJqZWN0IjogewogICAgImlkIjogIiR7X2hvbGRlcklkfSIsCiAgICAiZnVsbE5hbWUiOiAiJHtmdWxsTmFtZX0iLAogICAgInBvbGljeU51bWJlciI6ICIke3BvbGljeU51bWJlcn0iLAogICAgInBsYW4iOiAiJHtwbGFufSIsCiAgICAiY292ZXJhZ2VWYWxpZFVudGlsIjogIiR7Y292ZXJhZ2VWYWxpZFVudGlsfSIKICB9Cn0=',
    NULL,
    NULL,
    'https://www.w3.org/2018/credentials/v1,https://viitoradmin.github.io/inji-digital-health-id/contexts/insurance.json',
    'InsuranceCredential,VerifiableCredential',
    'ldp_vc',
    'did:web:viitoradmin.github.io:inji-digital-health-id:inji-issuer',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "Health Insurance Card", "locale": "en", "logo": {"url": "https://api.collab.mosip.net/inji/mosip-logo.png", "alt_text": "Health Authority Logo"}, "background_color": "#107c41", "text_color": "#FFFFFF"}]'::JSONB,
    ARRAY['fullName', 'policyNumber', 'plan', 'coverageValidUntil'],
    'insurance_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"fullName": {"display": [{"name": "Full Name", "locale": "en"}]}, "policyNumber": {"display": [{"name": "Policy Number", "locale": "en"}]}, "plan": {"display": [{"name": "Plan", "locale": "en"}]}, "coverageValidUntil": {"display": [{"name": "Valid Until", "locale": "en"}]}}'::JSONB,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NULL
);
