dbUserPasswords:
  dbuserPassword: ""

databases:
  inji_verify:
    enabled: true
    scriptsDir: inji_verify        # fixed - must match db_scripts/ folder in repo
    dbName: inji_verify            # customize e.g. inji_verify02
    dbUser: injiverifyuser         # customize e.g. injiverifyuser02
    defaultDb: postgres
    host: "postgres-postgresql"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: https://github.com/mosip/inji-verify.git
    branch: develop
