package utils;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;

import javax.ws.rs.core.MediaType;

import io.mosip.testrig.apirig.utils.*;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.json.JSONArray;
import org.json.JSONObject;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.testng.SkipException;

import com.github.javafaker.Faker;

import io.mosip.testrig.apirig.dto.TestCaseDTO;
import io.restassured.response.Response;
import utils.testdatamanager.UINManager;

public class InjiWebUtil extends AdminTestUtil {

	private static final Logger logger = Logger.getLogger(InjiWebUtil.class);
	private static final AdminTestUtil adminTestUtil = new AdminTestUtil();
	private static final Faker faker = new Faker();
	private static String dobForSunBirdR = generateDobForSunBirdR();

	public static void setLogLevel() {
		if (InjiWebConfigManager.IsDebugEnabled())
			logger.setLevel(Level.ALL);
		else
			logger.setLevel(Level.ERROR);
	}

	public static TestCaseDTO isTestCaseValidForTheExecution(TestCaseDTO testCaseDTO) {
		String testCaseName = testCaseDTO.getTestCaseName();
		
		currentTestCaseName = testCaseName; 

		int indexof = testCaseName.indexOf("_");
		String modifiedTestCaseName = testCaseName.substring(indexof + 1);

		addTestCaseDetailsToMap(modifiedTestCaseName, testCaseDTO.getUniqueIdentifier());

		String endpoint = testCaseDTO.getEndPoint();
		String inputJson = testCaseDTO.getInput();

		if (SkipTestCaseHandler.isTestCaseInSkippedList(testCaseName)) {
			throw new SkipException(GlobalConstants.KNOWN_ISSUES);
		}
		return testCaseDTO;
	}

	public static String inputstringKeyWordHandeler(String jsonString, String testCaseName) {

		if (jsonString.contains(GlobalConstants.TIMESTAMP)) {
			jsonString = replaceKeywordWithValue(jsonString, GlobalConstants.TIMESTAMP, generateCurrentUTCTimeStamp());
		}

		if (jsonString.contains("$POLICYNUMBERFORSUNBIRDRC$")) {
			String policyNumberForSunBirdR = generateRandomNumberString(9);
			jsonString = replaceKeywordWithValue(jsonString, "$POLICYNUMBERFORSUNBIRDRC$", policyNumberForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "POLICY", policyNumberForSunBirdR);
		}

		if (jsonString.contains("$FULLNAMEFORSUNBIRDRC$")) {
			String fullNameForSunBirdR = generateFullNameForSunBirdR();
			jsonString = replaceKeywordWithValue(jsonString, "$FULLNAMEFORSUNBIRDRC$", fullNameForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "NAME", fullNameForSunBirdR);
		}

		if (jsonString.contains("$DOBFORSUNBIRDRC$")) {
			jsonString = replaceKeywordWithValue(jsonString, "$DOBFORSUNBIRDRC$", dobForSunBirdR);
			adminTestUtil.writeAutoGeneratedId(testCaseName, "DOB", dobForSunBirdR);
		}

		return jsonString;

	}

	public static String generateFullNameForSunBirdR() {
		return faker.name().fullName();
	}

	public static String generateDobForSunBirdR() {
		LocalDate dob = faker.date().birthday().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
		return dob.format(DateTimeFormatter.ISO_LOCAL_DATE);
	}

	private static JSONArray mimotoActuatorResponseArray = null;
	private static final Object ACTUATOR_LOCK = new Object();

	public static String getValueFromMimotoActuator(String section, String key) {
		String url = ApplnURI + ConfigManager.getproperty("actuatorMimotoEndpoint");
		String useOldUrl = System.getenv("useOldContextURL");
		if (useOldUrl != null && !useOldUrl.isBlank() && useOldUrl.equalsIgnoreCase("true")) {
			url = url.replace("/v1/mimoto/", "/residentmobileapp/");
		}
		String actuatorCacheKey = url + section + key;
		String value = actuatorValueCache.get(actuatorCacheKey);
		if (value != null && !value.isEmpty())
			return value;

		try {
			synchronized (ACTUATOR_LOCK) {
				if (mimotoActuatorResponseArray == null) {
					Response response = RestClient.getRequest(url, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON);
					JSONObject responseJson = new JSONObject(response.getBody().asString());
					mimotoActuatorResponseArray = responseJson.getJSONArray("propertySources");
				}
			}
			for (int i = 0, size = mimotoActuatorResponseArray.length(); i < size; i++) {
				JSONObject eachJson = mimotoActuatorResponseArray.getJSONObject(i);
				if (eachJson.get("name").toString().contains(section)) {
					value = eachJson.getJSONObject(GlobalConstants.PROPERTIES).getJSONObject(key)
							.get(GlobalConstants.VALUE).toString();
					break;
				}
			}
			actuatorValueCache.put(actuatorCacheKey, value);
			return value;
		} catch (Exception e) {
			return "";
		}
	}

	public static String getSunbirdBaseURL() {
		return InjiWebUtil.getValueFromMimotoActuator("overrides", "mosip.sunbird.url");
	}

	public static TestCaseDTO changeContextURLByFlag(TestCaseDTO testCaseDTO) {
		if (!(System.getenv("useOldContextURL") == null) && !(System.getenv("useOldContextURL").isBlank())
				&& System.getenv("useOldContextURL").equalsIgnoreCase("true")) {
			if (testCaseDTO.getEndPoint().contains("/v1/mimoto/")) {
				testCaseDTO.setEndPoint(testCaseDTO.getEndPoint().replace("/v1/mimoto/", "/residentmobileapp/"));
			}
			if (testCaseDTO.getInput().contains("/v1/mimoto/")) {
				testCaseDTO.setInput(testCaseDTO.getInput().replace("/v1/mimoto/", "/residentmobileapp/"));
			}
		}

		return testCaseDTO;
	}

	public static String getCredentialConfigKey(String wellKnownUrl) {
		try {
			Response response = RestClient.getRequest(wellKnownUrl, MediaType.APPLICATION_JSON,
					MediaType.APPLICATION_JSON);
			JSONObject json = new JSONObject(response.getBody().asString());
			return json.getJSONObject("credential_configurations_supported").keys().next();
		} catch (Exception e) {
			logger.error("Failed to fetch credential configuration from URL: " + wellKnownUrl, e);
			return "default";
		}
	}

	public static HashMap<String, Integer> getActuatorValues(HashMap<String, String> keyMapping) {
		HashMap<String, Integer> result = new HashMap<>();
		String actuatorUrl = ConfigManager.getproperty("apiInternalEndPoint")
				+ ConfigManager.getproperty("actuatorMimotoEndpoint");
		logger.info("Actuator URL: " + actuatorUrl);
		Response response = RestClient.getRequest(actuatorUrl, MediaType.APPLICATION_JSON, MediaType.APPLICATION_JSON);
		if (response.getStatusCode() != 200) {
			throw new RuntimeException("Failed to fetch actuator values. HTTP error: " + response.getStatusCode());
		}

		JSONObject root = new JSONObject(response.getBody().asString());

		if (!root.has("propertySources")) {
			throw new RuntimeException("[ERROR] No propertySources found in actuator response!");
		}

		for (Object srcObj : root.getJSONArray("propertySources")) {
			if (!(srcObj instanceof JSONObject))
				continue;

			JSONObject src = (JSONObject) srcObj;
			JSONObject props = src.optJSONObject("properties");
			if (props == null)
				continue;

			for (String actuatorKey : keyMapping.keySet()) {
				String resultKey = keyMapping.get(actuatorKey);

				if (!result.containsKey(resultKey) && props.has(actuatorKey)) {
					String rawValue = props.getJSONObject(actuatorKey).optString("value", "0");

					try {
						int intValue = Integer.parseInt(rawValue.trim());
						result.put(resultKey, intValue);
					} catch (NumberFormatException e) {
						System.err
								.println("[WARN] Failed to parse value for key " + actuatorKey + " (" + rawValue + ")");
					}
				}
			}
			if (result.size() == keyMapping.size()) {
				logger.info("All keys mapped successfully");
				break;
			}
		}
		if (result.isEmpty()) {
			logger.info("No actuator values matched the provided key mapping.\"");
		}

		return result;
	}

	public String getOtp(String email, String phone) {
		String channelConfig = InjiWebConfigManager.getproperty("mockNotificationChannel");

		if (channelConfig == null || channelConfig.isBlank()) {
			throw new IllegalArgumentException("mockNotificationChannel is not configured");
		}

		String channel = channelConfig.toLowerCase();

		// Preference order: email > phone
		if (channel.contains("email")) {
			return NotificationListener.getOtp(email);
		} else if (channel.contains("phone")) {
			return NotificationListener.getOtp(phone);
		} else {
			throw new IllegalArgumentException("Unknown OTP channel: " + channelConfig);
		}
	}

	public String uinGetOtp() {
		return getOtp(UINManager.getEmail(), UINManager.getPhone());
	}

	public String resolveAcceptedDateOfBirthFormat(String rawDate, WebElement dobField) {
		if (rawDate == null || rawDate.trim().isEmpty()) {
			return rawDate;
		}

		String trimmedDate = rawDate.trim();
		if (!trimmedDate.matches("\\d{4}-\\d{2}-\\d{2}")) {
			return trimmedDate;
		}

		LocalDate parsedDate = LocalDate.parse(trimmedDate);
		for (String datePattern : resolveCandidateDatePatterns(dobField)) {
			String formattedDob = parsedDate.format(DateTimeFormatter.ofPattern(datePattern));
			if (tryDateCandidate(dobField, formattedDob, parsedDate)) {
				return formattedDob;
			}
		}

		return parsedDate.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
	}

	private List<String> resolveCandidateDatePatterns(WebElement dobField) {
		LinkedHashSet<String> candidatePatterns = new LinkedHashSet<>();
		String placeholderPattern = sanitizePattern(dobField.getAttribute("placeholder"));
		if (placeholderPattern != null) {
			candidatePatterns.add(placeholderPattern);
			candidatePatterns.addAll(withAlternateSeparators(placeholderPattern));
		}

		String browserPattern = resolvePatternFromBrowserLocale();
		if (browserPattern != null) {
			candidatePatterns.add(browserPattern);
			candidatePatterns.addAll(withAlternateSeparators(browserPattern));
		}

		candidatePatterns.add("dd-MM-yyyy");
		candidatePatterns.add("MM-dd-yyyy");
		candidatePatterns.add("dd/MM/yyyy");
		candidatePatterns.add("MM/dd/yyyy");
		candidatePatterns.add("yyyy-MM-dd");

		return new ArrayList<>(candidatePatterns);
	}

	private String resolvePatternFromBrowserLocale() {
		try {
			BaseTest baseTest = new BaseTest();
			Object result = ((JavascriptExecutor) baseTest.getDriver()).executeScript(
					"const locale = (navigator.languages && navigator.languages.length ? navigator.languages[0] : navigator.language) || 'en-US';"
							+ "return new Intl.DateTimeFormat(locale).format(new Date(1983, 10, 23));");

			if (!(result instanceof String sampleDate) || sampleDate.trim().isEmpty()) {
				return null;
			}

			return derivePatternFromFormattedSample(sampleDate.trim());
		} catch (Exception e) {
			return null;
		}
	}

	private String derivePatternFromFormattedSample(String sampleDate) {
		String separator = sampleDate.replaceAll(".*?(\\D+).*", "$1");
		String[] parts = sampleDate.split("\\D+");
		if (parts.length != 3) {
			return null;
		}

		String[] tokens = new String[3];
		boolean[] used = new boolean[3];

		for (int i = 0; i < parts.length; i++) {
			String part = parts[i];
			if ("1983".equals(part)) {
				tokens[i] = "yyyy";
				used[i] = true;
			} else if ("23".equals(part)) {
				tokens[i] = "dd";
				used[i] = true;
			} else if ("11".equals(part)) {
				tokens[i] = "MM";
				used[i] = true;
			}
		}

		for (int i = 0; i < used.length; i++) {
			if (!used[i]) {
				return null;
			}
		}

		String normalizedSeparator = separator == null || separator.trim().isEmpty() ? "/" : separator.substring(0, 1);
		return String.join(normalizedSeparator, tokens);
	}

	private String sanitizePattern(String candidatePattern) {
		if (candidatePattern == null || candidatePattern.trim().isEmpty()) {
			return null;
		}

		String normalized = candidatePattern.trim()
				.replaceAll("(?i)day", "dd")
				.replaceAll("(?i)month", "MM")
				.replaceAll("(?i)year", "yyyy")
				.replaceAll("d+", "dd")
				.replaceAll("M+", "MM")
				.replaceAll("y+", "yyyy");

		String separator = normalized.replaceAll("[dMy]", "");
		String normalizedSeparator = separator.isEmpty() ? "/" : separator.substring(0, 1);
		String compact = normalized.replaceAll("[^dMy]+", normalizedSeparator);
		String[] parts = compact.split(java.util.regex.Pattern.quote(normalizedSeparator));
		if (parts.length != 3) {
			return null;
		}

		if (isValidDateToken(parts[0]) && isValidDateToken(parts[1]) && isValidDateToken(parts[2])) {
			return String.join(normalizedSeparator, parts);
		}

		return null;
	}

	private boolean isValidDateToken(String token) {
		return "dd".equals(token) || "MM".equals(token) || "yyyy".equals(token);
	}

	private List<String> withAlternateSeparators(String pattern) {
		List<String> variants = new ArrayList<>();
		if (pattern == null || pattern.trim().isEmpty()) {
			return variants;
		}

		String tokenizedPattern = pattern.replace('/', '|').replace('-', '|').replace('.', '|');
		variants.add(tokenizedPattern.replace('|', '-'));
		variants.add(tokenizedPattern.replace('|', '/'));
		variants.add(tokenizedPattern.replace('|', '.'));
		return variants;
	}

	private boolean tryDateCandidate(WebElement dobField, String candidateValue, LocalDate expectedDate) {
		try {
			dobField.clear();
			dobField.sendKeys(candidateValue);
			dobField.sendKeys(Keys.TAB);

			String actualValue = dobField.getAttribute("value");
			if (actualValue == null || actualValue.trim().isEmpty()) {
				return false;
			}

			String normalizedActual = normalizeDateValue(actualValue);
			String normalizedCandidate = normalizeDateValue(candidateValue);
			if (normalizedActual.equals(normalizedCandidate)) {
				return true;
			}

			return doesFieldValueMatchExpectedDate(actualValue, expectedDate);
		} catch (Exception e) {
			return false;
		}
	}

	private boolean doesFieldValueMatchExpectedDate(String actualValue, LocalDate expectedDate) {
		String[] candidatePatterns = {"dd-MM-yyyy", "MM-dd-yyyy", "dd/MM/yyyy", "MM/dd/yyyy", "yyyy-MM-dd", "dd.MM.yyyy", "MM.dd.yyyy"};
		for (String pattern : candidatePatterns) {
			try {
				LocalDate parsedActual = LocalDate.parse(actualValue.trim(), DateTimeFormatter.ofPattern(pattern));
				if (expectedDate.equals(parsedActual)) {
					return true;
				}
			} catch (DateTimeParseException ignored) {
			}
		}
		return false;
	}

	private String normalizeDateValue(String dateValue) {
		return dateValue == null ? "" : dateValue.replaceAll("\\D", "");
	}

	public static File waitAndDownloadFile(JavascriptExecutor jse,
	                                       String fileName,
	                                       int timeoutSeconds,
	                                       int pollIntervalMillis) throws Exception {

		long startTime = System.currentTimeMillis();
		String base64EncodedFile = null;

		while ((System.currentTimeMillis() - startTime) < timeoutSeconds * 1000L) {

			// 1️⃣ Check if file exists in BrowserStack VM
			Object exists = jse.executeScript(
					"browserstack_executor: {\"action\": \"fileExists\", \"arguments\": {\"fileName\": \"" + fileName + "\"}}"
			);

			if (exists != null && exists.toString().equalsIgnoreCase("true")) {

				// 2️⃣ (Optional) Get metadata - size, last modified etc.
				Object properties = jse.executeScript(
						"browserstack_executor: {\"action\": \"getFileProperties\", \"arguments\": {\"fileName\": \"" + fileName + "\"}}"
				);

				System.out.println("File properties: " + properties);

				// 3️⃣ Fetch file content as Base64
				base64EncodedFile = (String) jse.executeScript(
						"browserstack_executor: {\"action\": \"getFileContent\", \"arguments\": {\"fileName\": \"" + fileName + "\"}}"
				);

				if (base64EncodedFile != null && !base64EncodedFile.isEmpty()) {
					break;
				}
			}

			Thread.sleep(pollIntervalMillis);
		}

		if (base64EncodedFile == null) {
			throw new RuntimeException("❌ File not downloaded within timeout: " + fileName);
		}

		// 4️⃣ Convert Base64 → File
		byte[] data = Base64.getDecoder().decode(base64EncodedFile);
		File file = new File(System.getProperty("user.dir"), fileName);

		try (OutputStream stream = new FileOutputStream(file)) {
			stream.write(data);
		}

		return file;
	}

}
