package utils.testdatamanager;

import models.Policy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

public class PolicyManager {

    private static final Logger logger = LoggerFactory.getLogger(PolicyManager.class);

    // Thread-safe pool of available policies (policyNumber + name + dob)
    private static final BlockingQueue<Policy> availablePolicies = new LinkedBlockingQueue<>();

    // Tracks which Policy the current thread is holding
    private static final ThreadLocal<Policy> currentThreadPolicy = new ThreadLocal<>();

    static {
        for (int i = 1; i <= 2; i++) {
            String prefix = "SunBirdR_CreatePolicy_NOAUTH_Valid_Smoke_POLICY" + i + "_Sid_";
            String policyNumber = autoGeneratedIDValueCache.get(prefix + "POLICY");
            String name = autoGeneratedIDValueCache.get(prefix + "NAME");
            String dob = autoGeneratedIDValueCache.get(prefix + "DOB");

            if (policyNumber == null || name == null || dob == null) {
                throw new IllegalStateException("Missing generated policy data for prefix: " + prefix);
            }

            availablePolicies.add(new Policy(
                    policyNumber,
                    name,
                    dob));
        }
    }

    //Sample data, data can be passed in this way as well
//    static {
//        availablePolicies.add(new Policy("1234567", "Aman Shahi", "2026-03-04"));
//        availablePolicies.add(new Policy("12345678", "Aman Shahi", "2026-03-04"));
//        availablePolicies.add(new Policy("123456789", "Aman Shahi", "2026-03-04"));
//    }

    /**
     * Non-blocking acquisition. Returns null immediately if no Policy is free,
     * so the calling thread is never stalled and can move on to other work.
     * The acquired Policy (policyNumber + name + dob) is bound to the current
     * thread via ThreadLocal and can be retrieved with {@link #getCurrentPolicy()}.
     * Returns the already-held Policy if this thread already owns one, preventing
     * silent overwrites and pool leaks.
     */
    public static Policy tryAcquirePolicy() {
        Policy existing = currentThreadPolicy.get();
        if (existing != null) {
            logger.info("[Thread '{}'] Already holds a Policy – returning existing", Thread.currentThread().getName());
            return existing;
        }
        Policy policy = availablePolicies.poll();
        if (policy != null) {
            currentThreadPolicy.set(policy);
            logger.info("[Thread '{}'] Acquired Policy: {}", Thread.currentThread().getName(), policy.getPolicyNumber());
        } else {
            logger.warn("[Thread '{}'] No Policy available in pool – all are in use", Thread.currentThread().getName());
        }
        return policy;
    }

    /**
     * Blocking acquisition used by retry analyzers. Blocks up to {@code timeout} until
     * a Policy is available, then atomically binds it to the current thread's ThreadLocal.
     * This eliminates the race window that exists when using {@code waitForPolicy} +
     * {@code offerPolicy} — ownership is established before the retry is authorized.
     * Returns null on timeout or interrupt.
     */
    public static Policy blockingAcquirePolicy(long timeout, TimeUnit unit) throws InterruptedException {
        Policy existing = currentThreadPolicy.get();
        if (existing != null) {
            logger.info("[Thread '{}'] Already holds a Policy – returning existing for blocking acquire",
                    Thread.currentThread().getName());
            return existing;
        }
        Policy policy = availablePolicies.poll(timeout, unit);
        if (policy != null) {
            currentThreadPolicy.set(policy);
            logger.info("[Thread '{}'] Blocking-acquired Policy: {}", Thread.currentThread().getName(), policy.getPolicyNumber());
        }
        return policy;
    }

    /**
     * Returns the Policy currently held by the calling thread.
     * Returns null if no Policy was acquired on this thread.
     */
    public static Policy getCurrentPolicy() {
        return currentThreadPolicy.get();
    }

    /** Convenience — returns the policy number for the current thread's acquired Policy. */
    public static String getPolicyNumber() {
        Policy policy = currentThreadPolicy.get();
        return policy != null ? policy.getPolicyNumber() : null;
    }

    /** Convenience — returns the name for the current thread's acquired Policy. */
    public static String getName() {
        Policy policy = currentThreadPolicy.get();
        return policy != null ? policy.getName() : null;
    }

    /** Convenience — returns the DOB for the current thread's acquired Policy. */
    public static String getDob() {
        Policy policy = currentThreadPolicy.get();
        return policy != null ? policy.getDob() : null;
    }

    /**
     * Releases the Policy held by the current thread back to the pool.
     * Safe to call even when no Policy was acquired – it is a no-op in that case.
     */
    public static void releaseCurrentThreadPolicy() {
        Policy policy = currentThreadPolicy.get();
        if (policy != null) {
            availablePolicies.offer(policy);
            currentThreadPolicy.remove();
            logger.info("[Thread '{}'] Released Policy: {}", Thread.currentThread().getName(), policy.getPolicyNumber());
        }
    }

}