package utils.testdatamanager;

import models.Uin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

import static io.mosip.testrig.apirig.utils.AdminTestUtil.autoGeneratedIDValueCache;

public class UINManager {

    private static final Logger logger = LoggerFactory.getLogger(UINManager.class);

    // Thread-safe pool of available UINs (uin + phone + email)
    private static final BlockingQueue<Uin> availableUINs = new LinkedBlockingQueue<>();

    // Tracks which UIN (and its phone/email) the current thread is holding
    private static final ThreadLocal<Uin> currentThreadUIN = new ThreadLocal<>();

    static {
        int totalUINs = 3;
        for (int i = 1; i <= totalUINs; i++) {
            String prefix = "AddIdentity_withValidParameters_smoke_UIN" + i + "_Pos_";
            String uin = autoGeneratedIDValueCache.get(prefix + "UIN");
            String phone = autoGeneratedIDValueCache.get(prefix + "PHONE");
            String email = autoGeneratedIDValueCache.get(prefix + "EMAIL");
            if (uin == null || phone == null || email == null) {
                throw new IllegalStateException("Missing generated UIN data for prefix: " + prefix);
            }

            availableUINs.add(new Uin(
                    uin,
                    phone,
                    email
            ));
        }
    }

    //Sample data, data can be passed in this way as well
//    static {
//        availableUINs.add(new Uin("6379306910", "3602485447", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("2038930429", "+4317909080", "Mimoto_AddIdentity_Binding_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("3985781534", "1048876755", "Mimoto_AddIdentity_downloadIssuerCredential_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4517095619", "2002563005", "Mimoto_AddIdentity_downloadIssuerCredentialWithGoogleLogin_smoke_Pos_698_@mosip.net"));
//        availableUINs.add(new Uin("4527046734", "8548612682", "Mimoto_AddIdentity_withValidParameters_smoke_Pos_0cb_@mosip.net"));
//    }

    /**
     * Non-blocking acquisition. Returns null immediately if no UIN is free,
     * so the calling thread is never stalled and can move on to other work.
     * The acquired UIN (uin + phone + email) is bound to the current thread
     * via ThreadLocal and can be retrieved with {@link #getCurrentUIN()}.
     * Returns the already-held UIN if this thread already owns one, preventing
     * silent overwrites and pool leaks.
     */
    public static Uin tryAcquireUIN() {
        Uin existing = currentThreadUIN.get();
        if (existing != null) {
            logger.info("[Thread '{}'] Already holds a UIN – returning existing", Thread.currentThread().getName());
            return existing;
        }
        Uin uin = availableUINs.poll();
        if (uin != null) {
            currentThreadUIN.set(uin);
            logger.info("[Thread '{}'] Acquired UIN: {}", Thread.currentThread().getName(), uin.getUin());
        } else {
            logger.warn("[Thread '{}'] No UIN available in pool – all are in use", Thread.currentThread().getName());
        }
        return uin;
    }

    /**
     * Blocking acquisition used by retry analyzers. Blocks up to {@code timeout} until
     * a UIN is available, then atomically binds it to the current thread's ThreadLocal.
     * This eliminates the race window that exists when using {@code waitForUIN} +
     * {@code offerUIN} — ownership is established before the retry is authorized.
     * Returns null on timeout or interrupt.
     */
    public static Uin blockingAcquireUIN(long timeout, java.util.concurrent.TimeUnit unit)
            throws InterruptedException {
        Uin existing = currentThreadUIN.get();
        if (existing != null) {
            logger.info("[Thread '{}'] Already holds a UIN – returning existing for blocking acquire",
                    Thread.currentThread().getName());
            return existing;
        }
        Uin uin = availableUINs.poll(timeout, unit);
        if (uin != null) {
            currentThreadUIN.set(uin);
            logger.info("[Thread '{}'] Blocking-acquired UIN: {}", Thread.currentThread().getName(), uin.getUin());
        }
        return uin;
    }

    /**
     * Returns the UIN (including phone and email) currently held by the calling thread.
     * Returns null if no UIN was acquired on this thread.
     */
    public static Uin getCurrentUIN() {
        return currentThreadUIN.get();
    }

    /** Convenience — returns the UIN string for the current thread's acquired UIN. */
    public static String getUin() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getUin() : null;
    }

    /** Convenience — returns the phone for the current thread's acquired UIN. */
    public static String getPhone() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getPhone() : null;
    }

    /** Convenience — returns the email for the current thread's acquired UIN. */
    public static String getEmail() {
        Uin uin = currentThreadUIN.get();
        return uin != null ? uin.getEmail() : null;
    }

    /**
     * Releases the UIN held by the current thread back to the pool.
     * Safe to call even when no UIN was acquired – it is a no-op in that case.
     */
    public static void releaseCurrentThreadUIN() {
        Uin uin = currentThreadUIN.get();
        if (uin != null) {
            availableUINs.offer(uin);
            currentThreadUIN.remove();
            logger.info("[Thread '{}'] Released UIN: {}", Thread.currentThread().getName(), uin.getUin());
        }
    }

}
