INSERT INTO certify.credential_config (
    credential_config_key_id,
    config_id,
    status,
    vc_template,
    doctype,
    sd_jwt_vct,
    context,
    credential_type,
    credential_format,
    did_url,
    key_manager_app_id,
    key_manager_ref_id,
    signature_algo,
    signature_crypto_suite,
    sd_claim,
    display,
    display_order,
    scope,
    cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported,
    proof_types_supported,
    credential_subject,
    mso_mdoc_claims,
    plugin_configurations,
    credential_status_purpose,
    qr_settings,
    qr_signature_algo,
    cr_dtimes,
    upd_dtimes
)
VALUES (
    'HealthID',
    gen_random_uuid()::VARCHAR(255),
    'active',
    'eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vcGl5dXNoNzAzNC5naXRodWIuaW8vbXktZmlsZXMvZmFybWVyLmpzb24iXSwiaXNzdWVyIjoiJHtfaXNzdWVyfSIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJIZWFsdGhJRCJdLCJpc3N1YW5jZURhdGUiOiIke3ZhbGlkRnJvbX0iLCJleHBpcmF0aW9uRGF0ZSI6IiR7dmFsaWRVbnRpbH0iLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6IiR7X2hvbGRlcklkfSIsImZpcnN0TmFtZSI6IiR7Zmlyc3ROYW1lfSIsImxhc3ROYW1lIjoiJHtsYXN0TmFtZX0iLCJkYXRlT2ZCaXJ0aCI6IiR7ZGF0ZU9mQmlydGh9IiwiZ2VuZGVyIjoiJHtnZW5kZXJ9IiwiZW1haWwiOiIke2VtYWlsfSIsInBob25lTnVtYmVyIjoiJHtwaG9uZU51bWJlcn0ifX0=',
    NULL,
    NULL,
    'https://piyush7034.github.io/my-files/farmer.json,https://www.w3.org/2018/credentials/v1',
    'HealthID,VerifiableCredential',
    'ldp_vc',
    'did:web:certify-nginx',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "Health ID", "locale": "en", "logo": {"url": "https://mosip.github.io/inji-config/logos/agro-vertias-logo.png", "alt_text": "Health ID"}, "background_color": "#0d6efd", "text_color": "#FFFFFF", "background_image": {"uri": "https://mosip.github.io/inji-config/logos/agro-vertias-logo.png"}}]'::JSONB,
    ARRAY['id', 'firstName', 'lastName', 'dateOfBirth', 'gender', 'email', 'phoneNumber'],
    'health_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"id": {"display": [{"name": "Record ID", "locale": "en"}]}, "firstName": {"display": [{"name": "First Name", "locale": "en"}]}, "lastName": {"display": [{"name": "Last Name", "locale": "en"}]}, "dateOfBirth": {"display": [{"name": "Date of Birth", "locale": "en"}]}, "gender": {"display": [{"name": "Gender", "locale": "en"}]}, "email": {"display": [{"name": "Email", "locale": "en"}]}, "phoneNumber": {"display": [{"name": "Phone Number", "locale": "en"}]}}'::JSONB,
    NULL,
    '[]'::JSONB,
    ARRAY['revocation'],
    '[{"First Name": "${firstName}", "Last Name": "${lastName}", "Email": "${email}"}]'::JSONB,
    'EdDSA',
    NOW(),
    NULL
)
ON CONFLICT (credential_config_key_id) DO UPDATE SET
    status = EXCLUDED.status,
    vc_template = EXCLUDED.vc_template,
    context = EXCLUDED.context,
    credential_type = EXCLUDED.credential_type,
    credential_format = EXCLUDED.credential_format,
    did_url = EXCLUDED.did_url,
    display = EXCLUDED.display,
    display_order = EXCLUDED.display_order,
    scope = EXCLUDED.scope,
    credential_subject = EXCLUDED.credential_subject,
    qr_settings = EXCLUDED.qr_settings,
    upd_dtimes = NOW();
