apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  {{- end }}

data:
  {{- range $path, $_ := .Files.Glob "files/*.json" }}
    {{- if ne (base $path) "config.json" }}
    {{ base $path }}: {{ $.Files.Get $path | quote }}
    {{- end }}
    {{- end }}

    {{- $config := .Files.Get "files/config.json" | fromJson }}
    {{- $walletBaseUrl := .Values.walletBaseUrl }}

    {{- $updatedWallets := list }}

    {{- range $wallet := $config.WebWallets }}
    {{- if eq $wallet.id "inji-wallet" }}
    {{- $_ := set $wallet "walletBaseUrl" $walletBaseUrl }}
    {{- end }}
    {{- $updatedWallets = append $updatedWallets $wallet }}
    {{- end }}

    {{- $_ := set $config "WebWallets" $updatedWallets }}

    config.json: {{ $config | toJson | quote }}