/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVerifyRouteImport } from './routes/_app.verify'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppIssuanceRouteImport } from './routes/_app.issuance'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppCredentialsIndexRouteImport } from './routes/_app.credentials.index'
import { Route as AppCredentialsNewRouteImport } from './routes/_app.credentials.new'
import { Route as AppCredentialsIdRouteImport } from './routes/_app.credentials.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppIssuanceRoute = AppIssuanceRouteImport.update({
  id: '/issuance',
  path: '/issuance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIndexRoute = AppCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsNewRoute = AppCredentialsNewRouteImport.update({
  id: '/credentials/new',
  path: '/credentials/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIdRoute = AppCredentialsIdRouteImport.update({
  id: '/credentials/$id',
  path: '/credentials/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/issuance': typeof AppIssuanceRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/verify': typeof AppVerifyRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/credentials/': typeof AppCredentialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/success': typeof SuccessRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/issuance': typeof AppIssuanceRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/verify': typeof AppVerifyRoute
  '/credentials/$id': typeof AppCredentialsIdRoute
  '/credentials/new': typeof AppCredentialsNewRoute
  '/credentials': typeof AppCredentialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/success': typeof SuccessRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/issuance': typeof AppIssuanceRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/verify': typeof AppVerifyRoute
  '/_app/credentials/$id': typeof AppCredentialsIdRoute
  '/_app/credentials/new': typeof AppCredentialsNewRoute
  '/_app/credentials/': typeof AppCredentialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/success'
    | '/analytics'
    | '/dashboard'
    | '/issuance'
    | '/records'
    | '/settings'
    | '/verify'
    | '/credentials/$id'
    | '/credentials/new'
    | '/credentials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/success'
    | '/analytics'
    | '/dashboard'
    | '/issuance'
    | '/records'
    | '/settings'
    | '/verify'
    | '/credentials/$id'
    | '/credentials/new'
    | '/credentials'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/success'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/issuance'
    | '/_app/records'
    | '/_app/settings'
    | '/_app/verify'
    | '/_app/credentials/$id'
    | '/_app/credentials/new'
    | '/_app/credentials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/verify': {
      id: '/_app/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/issuance': {
      id: '/_app/issuance'
      path: '/issuance'
      fullPath: '/issuance'
      preLoaderRoute: typeof AppIssuanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/': {
      id: '/_app/credentials/'
      path: '/credentials'
      fullPath: '/credentials/'
      preLoaderRoute: typeof AppCredentialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/new': {
      id: '/_app/credentials/new'
      path: '/credentials/new'
      fullPath: '/credentials/new'
      preLoaderRoute: typeof AppCredentialsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials/$id': {
      id: '/_app/credentials/$id'
      path: '/credentials/$id'
      fullPath: '/credentials/$id'
      preLoaderRoute: typeof AppCredentialsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIssuanceRoute: typeof AppIssuanceRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppCredentialsIdRoute: typeof AppCredentialsIdRoute
  AppCredentialsNewRoute: typeof AppCredentialsNewRoute
  AppCredentialsIndexRoute: typeof AppCredentialsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIssuanceRoute: AppIssuanceRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppCredentialsIdRoute: AppCredentialsIdRoute,
  AppCredentialsNewRoute: AppCredentialsNewRoute,
  AppCredentialsIndexRoute: AppCredentialsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
