package io.inji.verify.enums;

import lombok.Getter;

@Getter
public enum KBJwtErrorCodes {
    ERR_INVALID_KB_JWT_FORMAT,
    ERR_INVALID_KB_JWT_HEADER,
    ERR_INVALID_KB_JWT_ALG,
    ERR_INVALID_KB_JWT_TYP,
    ERR_INVALID_CNF,
    ERR_INVALID_CNF_TYPE,
    ERR_INVALID_CNF_KID,
    ERR_INVALID_KB_SIGNATURE,
    ERR_INVALID_AUD,
    ERR_INVALID_NONCE,
    ERR_INVALID_KB_JWT_IAT,
    ERR_INVALID_SD_HASH,
    ERR_CODE_MISSING_AUD,
    ERR_CODE_MISSING_NONCE,
    ERR_CODE_MISSING_IAT,
    ERR_CODE_MISSING_SD_HASH,
}
