require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")
xcode_env_path = File.join(__dir__, 'ios/.xcode.env')
require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = '1' if podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR'] == 'true'

platform :ios, podfile_properties['ios.deploymentTarget'] || '14'
install! 'cocoapods',
  :deterministic_uuids => false

prepare_react_native_project!

target 'Inji' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Note that if you have use_frameworks! enabled, Flipper will not work if enabled
  )

  post_install do |installer|
    # Xcode 26: Disable explicit modules for RNArgon2 compatibility
    installer.pods_project.targets.each do |target|
      if ['RNArgon2'].include?(target.name)
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        end
      end

      if target.name == 'RNZipArchive'
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            file.settings['COMPILER_FLAGS'] = ''
          end
        end
      end

      # Workaround `Cycle inside FBReactNativeSpec` error
      if target.name&.eql?('FBReactNativeSpec')
        target.build_phases.each do |build_phase|
          if build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs')
            target.build_phases.move(build_phase, 0)
          end
        end
      end

      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        defs = defs.is_a?(Array) ? defs : Array(defs)
        defs << '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION' unless defs.include?('_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION')
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = defs
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Sign resource bundles with NO code signing
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end

    # Inject ENABLE_AUTH into Info.plist
    plist_path = File.join(__dir__, 'Inji/Info.plist')
    if File.exist?(plist_path)
      require 'json'
      plist = JSON.parse(`plutil -convert json -o - "#{plist_path}"`)
      plist['ENABLE_AUTH'] = ENV['ENABLE_AUTH'] || 'true'
      File.open(plist_path, 'w') do |file|
        file.write(JSON.pretty_generate(plist))
      end
      system("plutil -convert xml1 #{plist_path}")
    else
      Pod::UI.warn "Info.plist not found at #{plist_path}"
    end

    # Apply development team from project to all pods
    dev_team = ""
    project = installer.aggregate_targets[0].user_project
    project.targets.each do |target|
      target.build_configurations.each do |config|
        if dev_team.empty? and !config.build_settings['DEVELOPMENT_TEAM'].nil?
          dev_team = config.build_settings['DEVELOPMENT_TEAM']
          break
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["DEVELOPMENT_TEAM"] = dev_team
      end
    end

    # Remove duplicate Assets.car from Copy Pods Resources phase
    project_path = './Inji.xcodeproj'
    project = Xcodeproj::Project.open(project_path)
    project.targets.each do |target|
      if target.name == "Inji"
        phase = target.shell_script_build_phases.find { |bp| bp.name == '[CP] Copy Pods Resources' }
        if !phase.nil?
          phase.output_paths.delete('${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Assets.car')
        end
      end
    end
    project.save(project_path)
  end

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-BluetoothPeripheral', :path => "#{permissions_path}/BluetoothPeripheral"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
end